/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DeferredContent: typeof import('primevue/deferredcontent')['default']
    FlagEditor: typeof import('./src/components/FlagEditor.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
  }
}
